kumuluzee:
  name: jdbc-primerjalnik-cen
  version: 1.0.0
  debug: true
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDB
      connection-url: jdbc:postgresql://localhost:5432/primerjalnik-cen
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  openapi-mp:
    ui:
      server-auto-config:
        enabled: true
        original-uri-check: true
  dev:
    scan-libraries:
      - models
      - lib
      - services
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/PrimerjalnikCenDB
        type: liveness
      disk-space-health-check:
        threshold: 100000000
  metrics:
    web-instrumentation:
      - name: izdelki-endpoint
        url-pattern: /v1/izdelki/*
      - name: trgovine-endpoint
        url-pattern: /v1/trgovine/*
      - name: vrste-endpoint
        url-pattern: /v1/vrste/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                           <Configuration name="comments">
                               <Appenders>
                                   <Console name="console" target="SYSTEM_OUT">
                                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                   </Console>
                                   <Socket name="logstash" host="625c2d49-19b3-438d-a67d-fc1d7398e073-ls.logit.io"
                                   port="15136" protocol="udp">
                                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                   </Socket>
                               </Appenders>
                               <Loggers>
                                   <!-- Default logger -->
                                   <Root level="all">
                                       <AppenderRef ref="console" level="info" />
                                       <AppenderRef ref="logstash" level="trace" />
                                   </Root>
                               </Loggers>
                           </Configuration>'
  config:
    consul:
      agent: http://localhost:8500
  rest-client:
    registrations:
      - class: kosarice-api
        url: http://localhost:8081/v1
        read-timeout: 5000
  streaming:
    kafka:
      producer:
        bootstrap-servers: glider.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: newer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="utvuvjbr" password="<hidden>";'
config-properties:
  maintenance-mode: false
  broken: false
  rapid-api:
    x-rapidapi-key:
    x-rapidapi-host:
  kosarice-api-url: http://localhost:8081/v1
