INSERT INTO vrsta(vrsta) VALUES ('Macbook Pro M1 Pro 512 GB');
INSERT INTO vrsta(vrsta) VALUES ('Bela Moka');
INSERT INTO vrsta(vrsta) VALUES ('Polnomastno mleko');
INSERT INTO trgovina(ime, ustanovitev, sedez) VALUES ('iStyle', '2012-01-01', 'Slovenia');
INSERT INTO trgovina(ime, ustanovitev, sedez) VALUES ('Harvey Norman', '1982-04-07', 'Australica');
INSERT INTO trgovina(ime, ustanovitev, sedez) VALUES ('Hofer', '1946-07-10', 'Germany');
INSERT INTO trgovina(ime, ustanovitev, sedez) VALUES ('Lidl', '1932-05-19', 'Germany');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('1', '1', 'iStyle Macbook', '249900', '2022-10-26');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('1', '2', 'Harvey Norman M1 Macbook', '269900', '2022-10-26');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('2', '3', 'Hofer bela moka', '96', '2022-10-26');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('2', '4', 'Lidl bela moka', '102', '2022-10-26');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('3', '3', 'Hofer polnomastno mleko', '93', '2022-10-26');
INSERT INTO izdelek(vrsta_id, trgovina_id, ime, cena, zadnja_sprememba) VALUES ('3', '4', 'Lidl polnomastno mleko', '93', '2022-10-26');
